---
title: "Viz"
author: "Sidd"
date: "April 9, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggjoy)
library(reshape2)
```


### Basic EDA for plots:


```{r}

# import clean data
suppressMessages(survey_results <- readRDS(file = '../data/processed/surveydata_clean.rds')) # local path - remove identifiers beforehand

# list expenditure categories
spending_cats <- c('living_expenses', 'savings', 'vacation', 'daily_leisure', 'consumption_goods', 
                           'sports_hobbies', 'other')

# converting char to numeric
survey_results$salary_base <- as.numeric(as.character(survey_results$salary_base))
survey_results$salary_expect <- as.numeric(as.character(survey_results$salary_expect))

# add ratio 
survey_results <- survey_results %>%  mutate(ratio = salary_expect/salary_base )


# remove outliers
survey_results <- survey_results %>% 
  filter(ratio < 10 & 
           ratio > 0.1)

survey_results[ , spending_cats][is.na(survey_results[,spending_cats])] <- 0

```



#### Histograms


### What is your country of employment/future employment? (used for determining currency for following questions)

-------------------------------- add percentages to plot
```{r, fig.width=10}

survey_country <- survey_results %>% select(country) %>% group_by(country) %>% summarise(count = n())

ggplot(survey_country)+
  geom_col(aes(x= reorder(country,count), y=count),width= 0.6, fill = "#FF8080") + 
    coord_flip() + labs(x = "Future Country of Employment", y = "Count" , title = "Future Country of Employment chosen by the respondents") + theme_minimal()

```





### Yes/No Responses for would you keep a job that does not give you a salary increase over the next two years assuming high job satisfaction

```{r, fig.width=10}

survey_yes_no <- survey_results %>% select(no_increase_acceptance) %>% group_by(no_increase_acceptance) %>% summarise(percent = n()/length(survey_results$no_increase_acceptance))
yes_no <- c("Yes","No")

ggplot(survey_yes_no) +
  geom_col(aes(x= reorder(no_increase_acceptance,percent), y=percent,fill = yes_no),width = 0.2) +
    coord_flip() + labs(x = "Choice", y = "Percent" , title = "Keeping a high satisfying job without a salary increase over next 2 years") +
      scale_y_continuous(labels = function(x) paste0(x*100, "%")) + 
        scale_fill_manual(guide = FALSE,values = c("Yes" = "cornflowerblue", "No" = "firebrick3"))+
          theme_minimal()



```



### Currently average yearly expenses to the following categories 

```{r}
# gathering data
survey_spendings<- survey_results %>% select(spending_cats) 
survey_results_spendings <- map_df(survey_spendings, as.numeric)
survey_results_spendings<- melt(survey_results_spendings)

survey_mean_yearly_expenses <- survey_results_spendings %>% select(variable,value) %>% group_by(variable) %>% summarise(mean(value))


colnames(survey_mean_yearly_expenses) <- c('Spending_Type', 'Average_Spending')

```


------------- include confidence interval
------------- colorbrewer 
```{r, fig.width=10}
ggplot(survey_mean_yearly_expenses) +
  geom_col(aes(x= reorder(Spending_Type,Average_Spending), y=Average_Spending,fill = survey_mean_yearly_expenses$Spending_Type),width = 0.5) +
    coord_flip() + labs(x = "Choice", y = "Percent" , title = "Yearly expenses") +
      scale_y_continuous(labels = function(x) paste0(x, "%")) + 
        scale_fill_manual(guide = FALSE,values = c("living_expenses" = "cornflowerblue", "savings" = "firebrick3","vacation" = "black","daily_leisure" ="coral2","consumption_goods"= "blue","sports_hobbies"= "pink","other" ="green"))+
        scale_x_discrete(breaks = c("living_expenses","savings","vacation","daily_leisure","consumption_goods","sports_hobbies","other"),labels=c("Living   Expenses","Savings","Vacation","Daily Leisure","Consumption Goods","Sports Hobbies","Other") ) +
          theme_minimal()
```





### Distribution of our ratios

----------------# show outliers
```{r}
ggplot(survey_results,aes(ratio)) +
  geom_histogram(binwidth = .1, col = "black", fill = "cornflowerblue")
```





```{r}
ggplot(survey_results, aes(x = ratio, y = 1))+
  geom_joy(fill = "cornflowerblue")

```




### Joy Plot for the distribution of the spendings per user. 

```{r, fig.width=10}


survey_results_spendings <- survey_results %>% select(spending_cats)

survey_results_spendings <- map_df(survey_results_spendings, as.numeric)

survey_results_spendings<- melt(survey_results_spendings)

# spending percentages
ggplot(survey_results_spendings, aes(x = value, y = variable, height = ..density.., fill = variable ))+
  geom_joy(stat = "density")+
    scale_y_discrete(breaks = c("living_expenses","savings","vacation","daily_leisure","consumption_goods","sports_hobbies","other"),labels=c("Living   Expenses","Savings","Vacation","Daily Leisure","Consumption Goods","Sports Hobbies","Other")) +
  theme(legend.position = "None")

```







