---
title: "Analysis Workflow"
author: "VM"
date: "April 11, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Main focus of EDA

* Trying to create a convincing narative for following analysis
* Look for stuff that don't add up
* these two things to highly dependent on each other
* not enough data 
* discussion of the survey
* pandas.describe as the summary table
* justify that we can do what we want with the data


Confounding -- 
How are we evaluating money drive.

Vector on a simplex that forms its own probability mass on a function. Because we are working
probability mass function where every one sums to 1. Because we have n-1 because 
we can always determine the effect of the last one 
linear model with a kernel on top.


Is it appropriate to make a linear model

n-1 ----------- 

if we have a bias, which we do, we dont need the last one

living in vancouver - confounding variables

new phds students
new or young working professionals can be confounding. 

pick out the confounding professionals 

How would you identify a young professional. 

Report Structure

# Preprocessing

The survey data was gathered through _Survey Monkey_ and exported locally for some anonymizing steps. Below is the code for this pre-cleaning.

```

```

For this workflow, the pre-processed data will be imported as follows:




# Exploratory Data Analysis

> 4 plots
- by country
- try to divide by age category through spending ratio

> A summary table

# Analysis

The data can be modeled with a multiple regression. 
A linear regression with multiple regressors can be especially prone to an important source of error: multicollinearity.

> (RANDOM EXAMPLE) Being young and being active (investing in sporting hobbies) could be an indication of being financially-driven which could hypothecally indicate a risk of multicollinearity if we had tracked an age metric, but without accounting for it, we could be dealing with a confounding variable. A solution to this problem could be to track all the information and divide the observations into sub-categories (or blocks?!?!?!?) that would treat each group differently depending on their age demographic. To monitor such confounding variables in the data acquired, an assessment of the variance of each variable in conjuction with the assessment of the response variable can be made. Stratification of the explanatory variable to run several conditional regression models would aim to reduce the bias due to confounding variables. 

Omitted variable bias would contribute to the error term in the model. It becomes a problem if the error term and the response variable are correlated. 

atrix values 
number of words proportion/probability in the data set
in NMF its not using these probabilities


CHECK THIS FOR THINGS NOT ACCOUNTED FOR
http://paperity.org/p/76870965/regression-analysis-of-household-expenditure-and-income


General multi reg reading
https://onlinelibrary.wiley.com/doi/pdf/10.1002/9781118856406.ch3

Example analysis and multicolinearity
https://smartech.gatech.edu/bitstream/handle/1853/53299/Regression_Analysis_of_the_Relationship_between_Income_and_Work_Hours-1.pdf

Other example 
http://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/BS704_Multivariable/BS704_Multivariable7.html

Multiple Linear Regression Analysis personal  spending
https://www.google.ca/search?ei=onDOWvyiKMT10wLRq7CAAg&q=Multiple+Linear+Regression+Analysis+personal++spending&oq=Multiple+Linear+Regression+Analysis+personal++spending&gs_l=psy-ab.3...3297877.3299652.0.3299818.8.8.0.0.0.0.149.677.6j2.8.0....0...1c.1.64.psy-ab..0.7.614...33i21k1j33i160k1.0.4e9Y0-Rozfs

# Discussion

# Conclusion