---
title: "Documentation"
author: "VM"
date: "April 11, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Main focus of EDA

* Trying to create a convincing narative for following analysis
* Look for stuff that don't add up
* these two things to highly dependent on each other
* not enough data 
* discussion of the survey
* pandas.describe as the summary table
* justify that we can do what we want with the data


Confounding -- 
How are we evaluating money drive.

Vector on a simplex that forms its own probability mass on a function. Because we are working
probability mass function where every one sums to 1. Because we have n-1 because 
we can always determine the effect of the last one 
linear model with a kernel on top.


Is it appropriate to make a linear model

n-1 ----------- 

if we have a bias, which we do, we dont need the last one

living in vancouver - confounding variables

new phds students
new or young working professionals can be confounding. 

pick out the confounding professionals 

How would you identify a young professional. 